/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
      "on-secondary-fixed-variant": "rgb(var(--on-secondary-fixed-variant) / <alpha-value>)",
      "on-secondary-fixed": "rgb(var(--on-secondary-fixed) / <alpha-value>)",
      "background": "rgb(var(--background) / <alpha-value>)",
      "inverse-primary": "rgb(var(--inverse-primary) / <alpha-value>)",
      "surface-container-low": "rgb(var(--surface-container-low) / <alpha-value>)",
      "tertiary-fixed-dim": "rgb(var(--tertiary-fixed-dim) / <alpha-value>)",
      "surface-dim": "rgb(var(--surface-dim) / <alpha-value>)",
      "surface": "rgb(var(--surface) / <alpha-value>)",
      "on-background": "rgb(var(--on-background) / <alpha-value>)",
      "tertiary": "rgb(var(--tertiary) / <alpha-value>)",
      "surface-bright": "rgb(var(--surface-bright) / <alpha-value>)",
      "secondary": "rgb(var(--secondary) / <alpha-value>)",
      "secondary-fixed-dim": "rgb(var(--secondary-fixed-dim) / <alpha-value>)",
      "surface-container-lowest": "rgb(var(--surface-container-lowest) / <alpha-value>)",
      "on-tertiary-fixed-variant": "rgb(var(--on-tertiary-fixed-variant) / <alpha-value>)",
      "on-primary": "rgb(var(--on-primary) / <alpha-value>)",
      "secondary-container": "rgb(var(--secondary-container) / <alpha-value>)",
      "primary": "rgb(var(--primary) / <alpha-value>)",
      "surface-container-high": "rgb(var(--surface-container-high) / <alpha-value>)",
      "on-primary-fixed-variant": "rgb(var(--on-primary-fixed-variant) / <alpha-value>)",
      "outline-variant": "rgb(var(--outline-variant) / <alpha-value>)",
      "primary-fixed-dim": "rgb(var(--primary-fixed-dim) / <alpha-value>)",
      "on-surface": "rgb(var(--on-surface) / <alpha-value>)",
      "inverse-surface": "rgb(var(--inverse-surface) / <alpha-value>)",
      "tertiary-fixed": "rgb(var(--tertiary-fixed) / <alpha-value>)",
      "tertiary-container": "rgb(var(--tertiary-container) / <alpha-value>)",
      "surface-container": "rgb(var(--surface-container) / <alpha-value>)",
      "primary-container": "rgb(var(--primary-container) / <alpha-value>)",
      "inverse-on-surface": "rgb(var(--inverse-on-surface) / <alpha-value>)",
      "on-tertiary": "rgb(var(--on-tertiary) / <alpha-value>)",
      "secondary-fixed": "rgb(var(--secondary-fixed) / <alpha-value>)",
      "on-surface-variant": "rgb(var(--on-surface-variant) / <alpha-value>)",
      "on-tertiary-container": "rgb(var(--on-tertiary-container) / <alpha-value>)",
      "error": "rgb(var(--error) / <alpha-value>)",
      "on-primary-fixed": "rgb(var(--on-primary-fixed) / <alpha-value>)",
      "error-container": "rgb(var(--error-container) / <alpha-value>)",
      "on-tertiary-fixed": "rgb(var(--on-tertiary-fixed) / <alpha-value>)",
      "surface-container-highest": "rgb(var(--surface-container-highest) / <alpha-value>)",
      "primary-fixed": "rgb(var(--primary-fixed) / <alpha-value>)",
      "outline": "rgb(var(--outline) / <alpha-value>)",
      "surface-tint": "rgb(var(--surface-tint) / <alpha-value>)",
      "on-primary-container": "rgb(var(--on-primary-container) / <alpha-value>)",
      "on-secondary": "rgb(var(--on-secondary) / <alpha-value>)",
      "on-error-container": "rgb(var(--on-error-container) / <alpha-value>)",
      "on-error": "rgb(var(--on-error) / <alpha-value>)",
      "surface-variant": "rgb(var(--surface-variant) / <alpha-value>)",
      "on-secondary-container": "rgb(var(--on-secondary-container) / <alpha-value>)"
},
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "sidebar-width": "280px",
              "space-xs": "0.25rem",
              "space-xl": "2rem",
              "space-sm": "0.5rem",
              "max-content-width": "800px",
              "space-md": "1rem",
              "space-lg": "1.5rem"
      },
      "fontFamily": {
              "label-md": ["Inter"],
              "body-md": ["Inter"],
              "headline-md": ["Hanken Grotesk"],
              "headline-lg": ["Hanken Grotesk"],
              "label-sm": ["Inter"],
              "body-lg": ["Inter"]
      },
      "fontSize": {
              "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "headline-lg": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
              "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
